services:
  app:
    container_name: ip-watcher
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CF_EMAIL=${CF_EMAIL}
      - CF_TOKEN=${CF_TOKEN}
      - TELEGRAM_BASE_URL=${TELEGRAM_BASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: unless-stopped